# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Berezha Security Official Blog
email: blog@berezhasecurity.com
description: > # this means to ignore newlines until "baseurl:"
  Berezha Security is an information security professional services company
  based in Kiev, Ukriane. Please visit https://berezhasecurity.com for more
  information. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://berezhasecurity.github.io" # the base hostname & protocol for your site
twitter_username: berezhasecurity
github_username:  berezhasecurity

# Build settings
markdown: kramdown
